name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  npm-package:
    name: NPM Package
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts

  gh-release:
    name: GitHub Release
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Read Changelog file
      run: npx @feryardiant/read-changelog > PUBLISH.txt

    - name: Publish
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: PUBLISH.txt
